=== jponge/izpack-full-svn-history-copy/izpack4/trunk/src/java/com/izforge/izpack/extension/extension-description.dtd
<!--

  DTD for an IzPack extension descriptor.

-->


<!-- The root element for an extension -->
<!ELEMENT extension (header, provides+)>

<!-- The extension header -->
<!ELEMENT header (name, description, url, license, author+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT license (#PCDATA)>

<!-- Specifies what the extension provides -->
<!ELEMENT provides (ident, what, class, jar+)>
<!ELEMENT ident (#PCDATA)>
<!ELEMENT what (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT jar (#PCDATA)>

=== jponge/izpack-full-svn-history-copy/izpack4/trunk/tests/java/com/izforge/izpack/extension/description.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE extension SYSTEM "http://www.izforge.com/izpack/dtd/extension-description.dtd">

<!--
  Part of the Extension class test case.
-->
<extension>

  <header>
    <name>SampleExtension</name>
    <description>It rulez.</description>
    <url>http://www.izforge.com/izpack/</url>
    <license>MIT</license>
    <author>Julien Ponge &lt;julien@izforge.com&gt;</author>
    <author>Julien Ponge &lt;julien_ponge@yahoo.fr&gt;</author>
  </header>

  <provides>
    <ident>SamplePanel1</ident>
    <what>com.izforge.izpack.panel</what>
    <class>com.izforge.izpack.foo.SamplePanel1</class>
    <jar>SamplePanel1.jar</jar>
    <jar>FooLib.jar</jar>
  </provides>

  <provides>
    <ident>SamplePanel2</ident>
    <what>com.izforge.izpack.panel</what>
    <class>com.izforge.izpack.foo.SamplePanel2</class>
    <jar>SamplePanel2.jar</jar>
    <jar>FooLib.jar</jar>
  </provides>

</extension>
